#!/usr/bin/env node

require('dotenv').config({ path: (__dirname + '/.env') });

var nodemailer = require("nodemailer"),
    moment = require('moment'),
    fs = require('fs'),
    path = require('path'),
    CronJob = require('cron').CronJob;


Mailer = {
  transporter: function(){
    return nodemailer.createTransport({
      service: 'Gmail',
      auth: {
        user: process.env.USER_EMAIL,
        pass: process.env.USER_PASS
      }
    })
  },

 emailText: function(){
   var greeting = 'Greetings, ' + process.env.RECIPIENT_NAME + ".\n\nThis is an automated email. Here is what I did today:\n\n";
   return greeting + fs.readFileSync(path.resolve(__dirname + '/today.txt'));
 },

 mailOptions: function(){
  var _self = this;
  return {
      from: process.env.SENDER_NAME + ' <' + process.env.USER_EMAIL + '>',
      to: process.env.RECIPIENT_EMAIL,
      cc: process.env.USER_EMAIL,
      subject: 'EOD email: ' + moment().format('dddd, MMMM Do, YYYY'),
      text: _self.emailText()
    }
  },

  sendMail: function(){
    var transporter = this.transporter();
    transporter.sendMail(this.mailOptions(), function(error, info){
      if(error){
        return console.log(error);
      }
      console.log('Message sent: ' + info.response);
    });
  }
}

var CronRunner = {
  run: function(){
    var job = new CronJob({
      cronTime: '30 17 * * 1-5',
      onTick: function() {
        Mailer.sendMail()
      },
      start: true,
      timeZone: 'America/Los_Angeles'
    });
  }
}

CronRunner.run();
