#!/usr/bin/env node

require('dotenv').config({ path: (__dirname + '/.env') });

var nodemailer = require("nodemailer"),
    moment = require('moment'),
    fs = require('fs'),
    path = require('path'),
    CronJob = require('cron').CronJob;


var transporter = nodemailer.createTransport({
    service: 'Gmail',
    auth: {
      user: process.env.USER_EMAIL,
      pass: process.env.USER_PASS
    }
});

var emailText = fs.readFileSync(path.resolve(__dirname + '/today.txt'));

var mailOptions = {
    from: process.env.USER_EMAIL,
    to: process.env.EMAIL_TO,
    subject: 'EOD email: ' + moment().format('dddd, MMMM Do, YYYY'),
    text: emailText
};

Mailer = {
  sendMail: function(){
    transporter.sendMail(mailOptions, function(error, info){
      if(error){
        return console.log(error);
      }
      console.log('Message sent: ' + info.response);
    });
  }
}

var job = new CronJob({
  cronTime: '*/3 * * * *',
  onTick: function() {
    Mailer.sendMail()
  },
  start: false,
  timeZone: 'America/Los_Angeles'
});
job.start();
